/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ArchiveDAO;
import DAO.OffreDAO;
import Entity.Adresse;
import Entity.Appartement;
import Entity.BienImmobilier;
import Entity.Entrepot;
import Entity.Gerant;
import Entity.Offre;
import Entity.Studio;
import Entity.Terrain;
import Entity.Villa;
import Technique.MapXA;
import Technique.PostFile;
import com.alee.global.GlobalConstants;
import com.alee.laf.WebLookAndFeel;
import com.alee.laf.filechooser.WebFileChooser;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class AjoutOffre extends javax.swing.JFrame {

    String fileName = null;
    public MapXA map = new MapXA();
    static int x = 0;
    OffreDAO offredao;
    List<Adresse> adresses;

    /**
     * Creates new form ListeOffres
     */
    public void refresh() {

        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        for (Adresse adresse : adresses) {

            dtm.addRow(new Object[]{adresse.getId(), adresse.getVille(), adresse.getGouvernorat(), adresse.getCode_pos()});

        }

    }

    /**
     * Creates new form NewJFrame
     */
    private AjoutOffre() {

    }

    public AjoutOffre(Gerant g) {
        g1 = g;
        initComponents();
        setDefaultCloseOperation(FileChooser.DISPOSE_ON_CLOSE);
        offredao = new OffreDAO();

        adresses = offredao.displayAllAdresse();

        refresh();
        WebLookAndFeel.install();
        WebLookAndFeel.setDecorateAllWindows(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPrix = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jType = new javax.swing.JComboBox();
        jSurface = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jNbr = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jMeuble = new javax.swing.JRadioButton();
        jMeuble1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jJardin = new javax.swing.JRadioButton();
        jChauffage1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jGaz = new javax.swing.JRadioButton();
        jE1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jE = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jC1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jC = new javax.swing.JRadioButton();
        jClim1 = new javax.swing.JRadioButton();
        jClim = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jChauffage = new javax.swing.JRadioButton();
        jJardin1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jA = new javax.swing.JRadioButton();
        jA1 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jNature = new javax.swing.JComboBox();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDescription = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jGaz1 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jMsg = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jRech = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jEtage = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jEtat = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuItem1.setText("jMenuItem1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Prix");

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Type ");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Surface");

        jPrix.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jPrix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPrixKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jType.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Appartement", "Studio", "Villa", "Terrain", "Entrepot" }));
        jType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTypeActionPerformed(evt);
            }
        });

        jSurface.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jSurface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSurfaceActionPerformed(evt);
            }
        });
        jSurface.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSurfaceKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Nombre De Pièces");

        jNbr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Meuble : ");

        jMeuble.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jMeuble.setText("Avec");
        jMeuble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeubleActionPerformed(evt);
            }
        });

        jMeuble1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jMeuble1.setText("Sans");
        jMeuble1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeuble1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Jardin : ");

        jJardin.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jJardin.setText("Avec");
        jJardin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJardinActionPerformed(evt);
            }
        });

        jChauffage1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jChauffage1.setText("Sans");
        jChauffage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChauffage1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Gaz De Ville :");

        jGaz.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jGaz.setText("Avec");
        jGaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGazActionPerformed(evt);
            }
        });

        jE1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jE1.setText("Sans");
        jE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jE1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Entrée Indépendate:");

        jE.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jE.setText("Avec");
        jE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Cuisine Equipe :");

        jC1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jC1.setText("Sans");
        jC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Climatisation :");

        jC.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jC.setText("Avec");
        jC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCActionPerformed(evt);
            }
        });

        jClim1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jClim1.setText("Sans");
        jClim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClim1ActionPerformed(evt);
            }
        });

        jClim.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jClim.setText("Avec");
        jClim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClimActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("Chauffage  :");

        jChauffage.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jChauffage.setText("Avec");
        jChauffage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChauffageActionPerformed(evt);
            }
        });

        jJardin1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jJardin1.setText("Sans");
        jJardin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJardin1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText("Ascenceur : ");

        jA.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jA.setText("Avec");
        jA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAActionPerformed(evt);
            }
        });

        jA1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jA1.setText("Sans");
        jA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jA1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText("Nature");

        jNature.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jNature.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vente", "Location" }));

        jTable2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ville", "Gouvenerat", "CodePostal"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel17.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 0));
        jLabel17.setText("Adresse :");

        jDescription.setColumns(20);
        jDescription.setRows(5);
        jScrollPane3.setViewportView(jDescription);

        jLabel18.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 0));
        jLabel18.setText("Description  :");

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Ajouter Une Offre");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nature", "Prix", "Type", "Surface", "Nbr De Pièces", "Ville", "Gouvernerat", "Code Postal"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable);

        jGaz1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jGaz1.setText("Sans");
        jGaz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGaz1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 0));
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 0));
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel21.setToolTipText("");
        jLabel21.setIcon(new ImageIcon(getClass().getResource("/images/upload.png")));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel22.setText("Choisir une image");

        jButton6.setText("Choisir la position");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel23.setText("Vous pouvez aussi préciser la position ici");

        jLabel24.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 0, 0));
        jLabel24.setText("Etage");

        jEtage.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jEtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtageActionPerformed(evt);
            }
        });
        jEtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEtageKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jEtageKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 0));
        jLabel25.setText("Etat");

        jEtat.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jEtat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nouveau", "Bon", "Mauvais" }));
        jEtat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(135, 135, 135)
                                            .addComponent(jButton3)
                                            .addGap(117, 117, 117)
                                            .addComponent(jButton4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel20)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addGap(221, 221, 221)
                                                                    .addComponent(jLabel15))
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(jLabel21))))
                                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(24, 24, 24)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel17)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jButton5)
                                                            .addGap(28, 28, 28)
                                                            .addComponent(jRech, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(14, 14, 14))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel23)
                                                    .addGap(85, 85, 85))))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jMsg)
                                    .addGap(123, 123, 123)
                                    .addComponent(jButton1)
                                    .addGap(659, 659, 659)))
                            .addComponent(jLabel18)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel13))
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSurface, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(276, 276, 276))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jNature, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGap(68, 68, 68))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(42, 42, 42)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel25)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel4)
                                                            .addComponent(jLabel24))
                                                        .addGap(38, 38, 38)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jEtage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jNbr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(45, 45, 45)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jChauffage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jJardin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jGaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jMeuble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMeuble1)
                                    .addComponent(jGaz1)
                                    .addComponent(jJardin1)
                                    .addComponent(jChauffage1))
                                .addGap(34, 34, 34)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jClim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jClim1)
                                    .addComponent(jA1)
                                    .addComponent(jC1)
                                    .addComponent(jE1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(jLabel14)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jEtage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jNbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(jNature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jMeuble1)
                                            .addComponent(jLabel8)
                                            .addComponent(jE, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jE1)
                                            .addComponent(jMeuble, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel9)
                                                .addComponent(jC)
                                                .addComponent(jC1)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jJardin, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jJardin1))
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(jGaz)
                                        .addComponent(jGaz1)
                                        .addComponent(jLabel10)
                                        .addComponent(jClim1)
                                        .addComponent(jClim, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jSurface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jChauffage)
                                .addComponent(jChauffage1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jA)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jA1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5)
                                .addComponent(jRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton3)
                                .addComponent(jButton4))
                            .addComponent(jMsg)
                            .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int m, j, g, c, e, ce, cl, a1;

        x++;
        jMsg.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if ((!jPrix.getText().trim().equals("")) && (!jSurface.getText().trim().equals(""))) {
            model.addRow(new Object[]{x, jNature.getSelectedItem().toString(), jPrix.getText(), jType.getSelectedItem().toString(), jSurface.getText(), jNbr.getSelectedItem().toString(), jTable2.getValueAt(jTable2.getSelectedRow(), 0), jTable2.getValueAt(jTable2.getSelectedRow(), 1), jTable2.getValueAt(jTable2.getSelectedRow(), 2)});
    }//GEN-LAST:event_jButton1ActionPerformed
        else {
            jMsg.setText("Informations manquantes !");
        }
        //Insertion BD  
        if (jMeuble.isSelected()) {
            m = 1;
        } else {
            m = 0;
        }
        if (jJardin.isSelected()) {
            j = 1;
        } else {
            j = 0;
        }
        if (jGaz.isSelected()) {
            g = 1;
        } else {
            g = 0;
        }
        if (jChauffage.isSelected()) {
            c = 1;
        } else {
            c = 0;
        }
        if (jE.isSelected()) {
            e = 1;
        } else {
            e = 0;
        }
        if (jC.isSelected()) {
            ce = 1;
        } else {
            ce = 0;
        }
        if (jClim.isSelected()) {
            cl = 1;
        } else {
            cl = 0;
        }
        if (jA.isSelected()) {
            a1 = 1;
        } else {
            a1 = 0;
        }

        OffreDAO o = new OffreDAO();
        Date d1 = new Date();
        Date d2 = new Date();
        Date d3 = new Date();
        int i5 = (int) jTable2.getValueAt(jTable2.getSelectedRow(), 0);
        String ch5 = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 1);
        String ch6 = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 2);
        int i6 = (int) jTable2.getValueAt(jTable2.getSelectedRow(), 3);
        Adresse a = new Adresse(i5, ch5, ch6, i6);

        BienImmobilier b = new BienImmobilier();
        if (jType.getSelectedItem().toString().equals("Appartement")) {
            b = new Appartement(Float.parseFloat(jSurface.getText()), jEtat.getSelectedItem().toString(), a, jDescription.getText(), Integer.parseInt(jNbr.getSelectedItem().toString()), ce, g, c, m, cl, a1, Integer.parseInt(jEtage.getText()));
        } else if (jType.getSelectedItem().toString().equals("Studio")) {
            b = new Studio(Float.parseFloat(jSurface.getText()), jEtat.getSelectedItem().toString(), a, jDescription.getText(), Integer.parseInt(jNbr.getSelectedItem().toString()), ce, g, c, m, cl, a1, Integer.parseInt(jEtage.getText()), e);
        } else if (jType.getSelectedItem().toString().equals("Entrepot")) {
            b = new Entrepot(Float.parseFloat(jSurface.getText()), jEtat.getSelectedItem().toString(), a);

        } else if (jType.getSelectedItem().toString().equals("Villa")) {

            b = new Villa(Float.parseFloat(jSurface.getText()), jEtat.getSelectedItem().toString(), a, jDescription.getText(), Integer.parseInt(jNbr.getSelectedItem().toString()), ce, g, c, m, cl, a1, Integer.parseInt(jEtage.getText()), e);
        } else if (jType.getSelectedItem().toString().equals("Terrain")) {
            b = new Terrain(Float.parseFloat(jSurface.getText()), jEtat.getSelectedItem().toString(), a);

        }

        String ch1 = "http://localhost/image/" + fileName + ".png";

        Offre o1 = new Offre(Float.parseFloat(jPrix.getText()), jNature.getSelectedItem().toString(), 5, d1, d2, d3, g1, b, ch1, map.getPos());
        o.insertOffre(o1, b, a);
        
        // Archive
        int gerantIDArchive = g1.getId();
        new ArchiveDAO().addArchive(gerantIDArchive, d2, ch1);
    }

    private void jTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTypeActionPerformed

    private void jMeubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeubleActionPerformed
        if (jMeuble.isSelected()) {
            jMeuble1.setSelected(false);
        } else {
            jMeuble1.setSelected(true);
        }

    }//GEN-LAST:event_jMeubleActionPerformed

    private void jJardinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJardinActionPerformed
        if (jJardin.isSelected()) {
            jJardin1.setSelected(false);
        } else {
            jJardin1.setSelected(true);
        }
    }//GEN-LAST:event_jJardinActionPerformed

    private void jGazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGazActionPerformed
        if (jGaz.isSelected()) {
            jGaz1.setSelected(false);
        } else {
            jGaz1.setSelected(true);
        }
    }//GEN-LAST:event_jGazActionPerformed

    private void jEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEActionPerformed
        if (jE.isSelected()) {
            jE1.setSelected(false);
        } else {
            jE1.setSelected(true);
        }
    }//GEN-LAST:event_jEActionPerformed

    private void jCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCActionPerformed
        if (jC.isSelected()) {
            jC1.setSelected(false);
        } else {
            jC1.setSelected(true);
        }
    }//GEN-LAST:event_jCActionPerformed

    private void jClimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClimActionPerformed
        if (jClim.isSelected()) {
            jClim1.setSelected(false);
        } else {
            jClim1.setSelected(true);
        }
    }//GEN-LAST:event_jClimActionPerformed

    private void jChauffageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChauffageActionPerformed
        if (jChauffage.isSelected()) {
            jChauffage1.setSelected(false);
        } else {
            jChauffage1.setSelected(true);
        }
    }//GEN-LAST:event_jChauffageActionPerformed

    private void jAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAActionPerformed
        if (jA.isSelected()) {
            jA1.setSelected(false);
        } else {
            jA1.setSelected(true);
        }
    }//GEN-LAST:event_jAActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if (jTable.getSelectedRow() == -1) {
            if (jTable.getRowCount() == 0) {
                jMsg.setText("La table est vide !");
            } else {
                jMsg.setText("Tu dois selectionner un offre !");
            }

        } else {
            int id = jTable.getSelectedRowCount();
            OffreDAO o = new OffreDAO();
            o.getDateupdate(id);
            //upadatenature
            model.setValueAt(jNature.getSelectedItem().toString(), jTable.getSelectedRow(), 1);
            String ch1 = jNature.getSelectedItem().toString();
            o.updateNature(id, ch1);

            //updateprix  
            model.setValueAt(jPrix.getText(), jTable.getSelectedRow(), 2);
            String ch2 = jPrix.getText();
            Float f = Float.parseFloat(ch2);
            o.updatePrix(id, f);

            model.setValueAt(jType.getSelectedItem().toString(), jTable.getSelectedRow(), 3);
            String ch4 = jType.getSelectedItem().toString();
            o.updateType(id, ch4);
            //updatesurface 
            model.setValueAt(jSurface.getText(), jTable.getSelectedRow(), 4);
            String ch3 = jSurface.getText();
            Float f1 = Float.parseFloat(ch3);
            o.updateSurface(id, f1);

            model.setValueAt(jNbr.getSelectedItem().toString(), jTable.getSelectedRow(), 5);
            String ch5 = jNbr.getSelectedItem().toString();
            Integer i1 = Integer.parseInt(ch5);
            o.updateNbr(id, i1);
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if (jTable.getSelectedRow() == -1) {
            if (jTable.getRowCount() == 0) {
                jMsg.setText("La table est vide !");
            } else {
                jMsg.setText("Tu dois selectionner une offre !");
            }

        } else {
            OffreDAO o = new OffreDAO();
            String f = (String) model.getValueAt(jTable.getSelectedRow(), 2);
            float f1 = Float.parseFloat(f);
            String f3 = (String) model.getValueAt(jTable.getSelectedRow(), 4);
            float f2 = Float.parseFloat(f3);
            String ch = (String) model.getValueAt(jTable.getSelectedRow(), 5);
            Integer i = Integer.parseInt(ch);
            String ch1 = (String) model.getValueAt(jTable.getSelectedRow(), 1);

            o.deleteOffre1(f1, f2, ch1, i);
            model.removeRow(jTable.getSelectedRow());


    }//GEN-LAST:event_jButton4ActionPerformed
    }
    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        jNature.setSelectedItem(model.getValueAt(jTable.getSelectedRow(), 1).toString());
        jPrix.setText(model.getValueAt(jTable.getSelectedRow(), 2).toString());
        jType.setSelectedItem(model.getValueAt(jTable.getSelectedRow(), 3).toString());
        jSurface.setText(model.getValueAt(jTable.getSelectedRow(), 4).toString());
        jNbr.setSelectedItem(model.getValueAt(jTable.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_jTableMouseClicked

    private void jMeuble1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeuble1ActionPerformed
        if (jMeuble1.isSelected()) {
            jMeuble.setSelected(false);
        } else {
            jMeuble.setSelected(true);
        }
    }//GEN-LAST:event_jMeuble1ActionPerformed

    private void jJardin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJardin1ActionPerformed
        if (jJardin1.isSelected()) {
            jJardin.setSelected(false);
        } else {
            jJardin.setSelected(true);
        }
    }//GEN-LAST:event_jJardin1ActionPerformed

    private void jGaz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGaz1ActionPerformed
        if (jGaz1.isSelected()) {
            jGaz.setSelected(false);
        } else {
            jGaz.setSelected(true);
        }
    }//GEN-LAST:event_jGaz1ActionPerformed

    private void jChauffage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChauffage1ActionPerformed
        if (jChauffage1.isSelected()) {
            jChauffage.setSelected(false);
        } else {
            jChauffage.setSelected(true);
        }
    }//GEN-LAST:event_jChauffage1ActionPerformed

    private void jE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jE1ActionPerformed
        if (jE1.isSelected()) {
            jE.setSelected(false);
        } else {
            jE.setSelected(true);
        }
    }//GEN-LAST:event_jE1ActionPerformed

    private void jC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC1ActionPerformed
        if (jC1.isSelected()) {
            jC.setSelected(false);
        } else {
            jC.setSelected(true);
        }
    }//GEN-LAST:event_jC1ActionPerformed

    private void jClim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClim1ActionPerformed
        if (jClim1.isSelected()) {
            jClim.setSelected(false);
        } else {
            jClim.setSelected(true);
        }
    }//GEN-LAST:event_jClim1ActionPerformed

    private void jA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jA1ActionPerformed
        if (jA1.isSelected()) {
            jA.setSelected(false);
        } else {
            jA.setSelected(true);
        }
    }//GEN-LAST:event_jA1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        OffreDAO c = new OffreDAO();
        String ch = jRech.getText();
        List<Adresse> l = c.findAdresse(ch);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        for (Adresse adresse : l) {

            dtm.addRow(new Object[]{adresse.getId(), adresse.getVille(), adresse.getGouvernorat(), adresse.getCode_pos()});

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

    }//GEN-LAST:event_jTable2MouseClicked

    private void jPrixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPrixKeyReleased
        try {
            
           if (jPrix.getText().isEmpty() == false){float i = Float.parseFloat(jPrix.getText());}
           
        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(this, "Saisir un nombre");
        }
    }//GEN-LAST:event_jPrixKeyReleased

    private void jSurfaceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSurfaceKeyReleased
       try {
            
           if (jSurface.getText().isEmpty() == false){float i = Float.parseFloat(jSurface.getText());}
           
        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(this, "Saisir un nombre");
        }
    }//GEN-LAST:event_jSurfaceKeyReleased

    private void jSurfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSurfaceActionPerformed
        try {
            float i = Float.parseFloat(jPrix.getText());
        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(this, "Saisir un nombre");
        }
    }//GEN-LAST:event_jSurfaceActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked

        WebFileChooser f = new WebFileChooser();
        f.setVisible(true);

        File file = null;
        BufferedImage bi = null;
        BufferedImage bi1 = new BufferedImage(400, 200, BufferedImage.TRANSLUCENT);

        if (f == null) {
            f = new WebFileChooser();
            f.setMultiSelectionEnabled(false);
            f.setAcceptAllFileFilterUsed(true);
            f.addChoosableFileFilter(GlobalConstants.IMAGES_FILTER);
        }
        if (file != null) {
            f.setSelectedFile(file);
        }
        if (f.showOpenDialog(this) == WebFileChooser.APPROVE_OPTION) {
            file = f.getSelectedFile();
            try {
                bi = ImageIO.read(file);

                Graphics2D g2d = bi1.createGraphics();
                g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
                g2d.drawImage(bi, 0, 0, 400, 200, null);
                g2d.dispose();
            } catch (IOException ex) {
                Logger.getLogger(AjoutOffre.class.getName()).log(Level.SEVERE, null, ex);
            }
            fileName = UUID.randomUUID().toString();
            File outputfile = new File(fileName + ".png");
            try {
                ImageIO.write(bi1, "png", outputfile);
            } catch (IOException ex) {
                Logger.getLogger(AjoutOffre.class.getName()).log(Level.SEVERE, null, ex);
            }
//                    System.out.println(file);

            System.out.println(outputfile);
            try {
                new PostFile().upload(outputfile.toString());
            } catch (Exception ex) {
                Logger.getLogger(AjoutOffre.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jLabel21MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        map.Demmarer();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jEtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEtageKeyReleased
try {
            
           if (jEtage.getText().isEmpty() == false){float i = Float.parseFloat(jEtage.getText());}
           
        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(this, "Saisir un nombre");
        }    }//GEN-LAST:event_jEtageKeyReleased

    private void jEtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtageActionPerformed
      
        
    }//GEN-LAST:event_jEtageActionPerformed

    private void jEtatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEtatActionPerformed

    private void jEtageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEtageKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jEtageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                // Look and Feel 
                WebLookAndFeel.install();
                WebLookAndFeel.setDecorateAllWindows(true);

                new AjoutOffre(new Gerant("", "", 2, "", "", "nom", "prenom", "", "", (short) 1));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JRadioButton jA;
    private javax.swing.JRadioButton jA1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JRadioButton jC;
    private javax.swing.JRadioButton jC1;
    private javax.swing.JRadioButton jChauffage;
    private javax.swing.JRadioButton jChauffage1;
    private javax.swing.JRadioButton jClim;
    private javax.swing.JRadioButton jClim1;
    private javax.swing.JTextArea jDescription;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JRadioButton jE;
    private javax.swing.JRadioButton jE1;
    private javax.swing.JTextField jEtage;
    private javax.swing.JComboBox jEtat;
    private javax.swing.JRadioButton jGaz;
    private javax.swing.JRadioButton jGaz1;
    private javax.swing.JRadioButton jJardin;
    private javax.swing.JRadioButton jJardin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton jMeuble;
    private javax.swing.JRadioButton jMeuble1;
    private javax.swing.JLabel jMsg;
    private javax.swing.JComboBox jNature;
    private javax.swing.JComboBox jNbr;
    private javax.swing.JTextField jPrix;
    private javax.swing.JTextField jRech;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jSurface;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox jType;
    // End of variables declaration//GEN-END:variables
    private Gerant g1;
}
